source 'http://rubygems.org'

#gem 'admin_data', :git => 'git://github.com/neerajdotname/admin_data.git'
gem 'admin_data', :path => File.expand_path("../../..", __FILE__)

gem 'rails', '3.0.3'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'pg', '= 0.10.0'

gem "mysql2", '= 0.2.7'

gem 'ruby-debug'

gem 'faker'


gem 'factory_girl_rails'
gem 'database_cleaner'
gem 'shoulda'
gem "rspec-rails", ">= 2.0.1"
gem "cucumber-rails", ">= 0.3.2"
gem "capybara", "= 0.4.0"
gem "launchy", ">= 0.3.7"
gem 'minitest'
